/**:
  ros__parameters:
    sensor_height: 2.08
    num_iter: 3  # Number of iterations for ground plane estimation using PCA.
    num_lpr: 20  # Maximum number of points to be selected as lowest points representative.
    num_min_pts: 20  # Minimum number of points to be estimated as ground plane in each patch.
    th_seeds: 0.3
    # threshold for lowest point representatives using in initial seeds selection of ground points.
    th_dist: 0.125  # threshold for thickness of ground.
    th_seeds_v: 0.25
    # threshold for lowest point representatives using in initial seeds selection of vertical structural points.
    th_dist_v: 0.5  # threshold for thickness of vertical structure.
    max_range: 300.0  # max_range of ground estimation area
    min_range: 0.0  # min_range of ground estimation area
    uprightness_thr: 0.101
    # threshold of uprightness using in Ground Likelihood Estimation(GLE). Please refer paper for more information about GLE.
    base_link_proximity_radius: 10.0  # radius of base_link proximity filter
    max_ground_height: 0.5  # maximum allowed height of ground inside the base_link proximity filter
    verbose: True  # display verbose info
